# General
title: Proudly Serving
description: Public service with and for the people
url: https://proudlyservingbook.com
#baseurl: ""

# Sections
quotes-name: What they're saying
quotes-url: /what-theyre-saying
contributors-name: Contributors
contributors-url: /contributors
contents-name: Contents
contents-url: /book
about-name: Purpose
about-url: /about
book-name: book
book-url: /book
author-name: Author
author-url: /author

# Organization
org-name: Proudly Serving
org-url: https://proudlyservingbook.com

# Social
social:
  name: Proudly Serving
  links:
    - https://twitter.com/proudly_serving
    - https://www.linkedin.com/company/proudlyserving

twitter-username: proudly_serving
twitter: "@proudly_serving"
linkedin: https://www.linkedin.com/company/proudlyserving

# Date/time
date: "%B %-d, %Y"
timezone: America/Los_Angeles

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from
  
# Defaults
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      folder: "News"
      img-path: "posts"
      parent: "news"
      layout: "post"
      short: "true"
      schematype: "NewsArticle"
  - scope:
      path: "_contents"
      type: "contents"
    values:
      folder: "Contents"
      img-path: "contents"
      parent: "contents"
      layout: "page"
      short: "true"
      schematype: "Article"
  - scope:
      path: "_contributors"
      type: "contributors"
    values:
      folder: "Contributors"
      img-path: "contributors"
      parent: "contributors"
      layout: "profile"
      short: "true"
      schematype: "ProfilePage"

# Collections
collections:
  pages:
    output: true
    permalink: :title
  posts:
    output: true
    permalink: /news/:title
  contributors:
    output: true
    permalink: contributors/:title
  contents:
    output: true
    permalink: contents/:title

# Pagination
paginate: 24
paginate_path: "/news/:num"

# Sections
sections:
  - "intro"
  - "chapters"
  - "about"
