# General
title: Proudly Serving
description: Public service in the digital age
#baseurl: ""
#url: ""

# Date/time
date: "%B %-d, %Y"
timezone: America/Los_Angeles

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  
# Defaults
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      folder: "News"
      img-path: "news"
      parent: "news"
      layout: "post"
      short: "true"
  - scope:
      path: "_contents"
      type: "contents"
    values:
      folder: "Contents"
      img-path: "contents"
      parent: "contents"
      layout: "page"
      short: "true"
  - scope:
      path: "_people"
      type: "people"
    values:
      folder: "People"
      img-path: "people"
      parent: "people"
      layout: "profile"
      short: "true"

# Collections
collections:
  pages:
    output: true
    permalink: :title
  posts:
    output: true
    permalink: /news/:title
  people:
    output: true
    permalink: people/:title
  contents:
    output: true
    permalink: contents/:title

# Pagination
paginate: 24
paginate_path: "/news/:num"

# Sections
sections:
  - "intro"
  - "chapters"
  - "about"
